name: Run Unittests on PR

on:
  pull_request:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'
      - '**.rst'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensures history is checked out for merge simulation

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unittests
        run: python -m unittest llmsherpa/readers/tests/test_layout_reader.py